FROM continuumio/miniconda3

# Install MLflow
RUN conda install -y -c conda-forge mlflow

# Salin file environment dan install environment
COPY conda.yml /tmp/conda.yml
RUN conda env create -f /tmp/conda.yml && conda clean -afy

# Tambahkan ke PATH
ENV PATH=/opt/conda/envs/mlflow-env/bin:$PATH

# Set direktori kerja
WORKDIR /app

# Salin semua file project ke container
COPY . /app

# Jalankan script modelling.py (yang sudah handle dagshub.init dan set_tracking_uri)
CMD ["python", "modelling.py"]