FROM continuumio/miniconda3

# Install MLflow
RUN conda install -y -c conda-forge mlflow

# Copy conda environment
COPY conda.yml /tmp/conda.yml
RUN conda env create -f /tmp/conda.yml && conda clean -afy

# Set conda env path
ENV PATH=/opt/conda/envs/mlflow-env/bin:$PATH

# Working directory
WORKDIR /app

# Copy project files
COPY . /app

# Expose port if needed (optional)
EXPOSE 5000

# Run training
CMD ["python", "modelling_tuning.py"]