name: Workflow-CI Skor Mahasiswa (Advanced)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  train-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yml
          auto-activate-base: false
          use-mamba: true

      - name: Run MLflow Project
        run: |
          mlflow run MLProject/ --env-manager=local --experiment-name=Student_performance_CI
        shell: bash -l {0}

      - name: Upload Best Model to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: best_model
          path: MLProject/models
          if-no-files-found: warn

  docker:
    needs: train-and-upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image with MLflow
        run: |
          mlflow build-docker -n student-performance-tuning -f MLProject/MLProject

      - name: Push Docker Image
        run: |
          docker tag student-performance-tuning ${{ secrets.DOCKER_USERNAME }}/workflow-ci:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/workflow-ci:latest